In [1]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/home/srikanth/anaconda3/lib/python3.8/site-packages/tensorflow/_api/v2/version/__init__.py'>


In [5]:
string = tf.Variable("hello",tf.string)
number=tf.Variable(324,tf.int16)
floating=tf.Variable(3.25,tf.float64)
string

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'hello'>

In [7]:
tensor1=tf.ones([1,2,3])
tensor1

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [8]:
tensor2=tf.reshape(tensor1,[2,3,1])
tensor2

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]], dtype=float32)>